@file:Suppress("MagicNumber")

package com.kleros.meaning

import com.kleros.dice.DiceType
import com.kleros.table.TableDef
import com.kleros.table.TableEntry

object MeaningData {

    val action: TableDef = TableDef(
        name = "Meaning Action",
        entries = listOf(
            TableEntry.RANGE(min = 1, max = 2, result = "Attain"),
            TableEntry.RANGE(min = 3, max = 4, result = "Start"),
            TableEntry.RANGE(min = 5, max = 6, result = "Neglect"),
            TableEntry.RANGE(min = 7, max = 8, result = "Fight"),
            TableEntry.RANGE(min = 9, max = 10, result = "Recruit"),
            TableEntry.RANGE(min = 11, max = 12, result = "Triumph"),
            TableEntry.RANGE(min = 13, max = 14, result = "Violate"),
            TableEntry.RANGE(min = 15, max = 16, result = "Oppose"),
            TableEntry.RANGE(min = 17, max = 18, result = "Malice"),
            TableEntry.RANGE(min = 19, max = 20, result = "Communicate"),
            TableEntry.RANGE(min = 21, max = 22, result = "Persecute"),
            TableEntry.RANGE(min = 23, max = 24, result = "Increase"),
            TableEntry.RANGE(min = 25, max = 26, result = "Decrease"),
            TableEntry.RANGE(min = 27, max = 28, result = "Abandon"),
            TableEntry.RANGE(min = 29, max = 30, result = "Gratify"),
            TableEntry.RANGE(min = 31, max = 32, result = "Inquire"),
            TableEntry.RANGE(min = 33, max = 34, result = "Antagonize"),
            TableEntry.RANGE(min = 35, max = 36, result = "Move"),
            TableEntry.RANGE(min = 37, max = 38, result = "Waste"),
            TableEntry.RANGE(min = 39, max = 40, result = "Truce"),
            TableEntry.RANGE(min = 41, max = 42, result = "Release"),
            TableEntry.RANGE(min = 43, max = 44, result = "Befriend"),
            TableEntry.RANGE(min = 45, max = 46, result = "Judge"),
            TableEntry.RANGE(min = 47, max = 48, result = "Desert"),
            TableEntry.RANGE(min = 49, max = 50, result = "Dominate"),
            TableEntry.RANGE(min = 51, max = 52, result = "Procrastinate"),
            TableEntry.RANGE(min = 53, max = 54, result = "Create"),
            TableEntry.RANGE(min = 55, max = 56, result = "Treachery"),
            TableEntry.RANGE(min = 57, max = 58, result = "Join"),
            TableEntry.RANGE(min = 59, max = 60, result = "Protect"),
            TableEntry.RANGE(min = 61, max = 62, result = "Break"),
            TableEntry.RANGE(min = 63, max = 64, result = "Aid"),
            TableEntry.RANGE(min = 65, max = 66, result = "Abuse"),
            TableEntry.RANGE(min = 67, max = 68, result = "Oppress"),
            TableEntry.RANGE(min = 69, max = 70, result = "Reject"),
            TableEntry.RANGE(min = 71, max = 72, result = "Continue"),
            TableEntry.RANGE(min = 73, max = 74, result = "Collaborate"),
            TableEntry.RANGE(min = 75, max = 76, result = "Delay"),
            TableEntry.RANGE(min = 77, max = 78, result = "Transform"),
            TableEntry.RANGE(min = 79, max = 80, result = "Submit"),
            TableEntry.RANGE(min = 81, max = 82, result = "Guide"),
            TableEntry.RANGE(min = 83, max = 84, result = "Divide"),
            TableEntry.RANGE(min = 85, max = 86, result = "Absorb"),
            TableEntry.RANGE(min = 87, max = 88, result = "Dispute"),
            TableEntry.RANGE(min = 89, max = 90, result = "Reveal"),
            TableEntry.RANGE(min = 91, max = 92, result = "Renounce"),
            TableEntry.RANGE(min = 93, max = 94, result = "Remember"),
            TableEntry.RANGE(min = 95, max = 96, result = "Betray"),
            TableEntry.RANGE(min = 97, max = 98, result = "Deceive"),
            TableEntry.RANGE(min = 99, max = 100, result = "Uncertain"),
        ),
    )

    val description: TableDef = TableDef(
        name = "Meaning Description",
        entries = listOf(
            TableEntry.RANGE(min = 1, max = 2, result = "Artificial"),
            TableEntry.RANGE(min = 3, max = 4, result = "Mundane"),
            TableEntry.RANGE(min = 5, max = 6, result = "New"),
            TableEntry.RANGE(min = 7, max = 8, result = "Important"),
            TableEntry.RANGE(min = 9, max = 10, result = "Trivial"),
            TableEntry.RANGE(min = 11, max = 12, result = "Unplanned"),
            TableEntry.RANGE(min = 13, max = 14, result = "Unjust"),
            TableEntry.RANGE(min = 15, max = 16, result = "Beneficial"),
            TableEntry.RANGE(min = 17, max = 18, result = "Expected"),
            TableEntry.RANGE(min = 19, max = 20, result = "Exposed"),
            TableEntry.RANGE(min = 21, max = 22, result = "Inevitable"),
            TableEntry.RANGE(min = 23, max = 24, result = "Close"),
            TableEntry.RANGE(min = 25, max = 26, result = "Uncomplicated"),
            TableEntry.RANGE(min = 27, max = 28, result = "Suspicious"),
            TableEntry.RANGE(min = 29, max = 30, result = "Temporary"),
            TableEntry.RANGE(min = 31, max = 32, result = "Threatening"),
            TableEntry.RANGE(min = 33, max = 34, result = "Limited"),
            TableEntry.RANGE(min = 35, max = 36, result = "Emotional"),
            TableEntry.RANGE(min = 37, max = 38, result = "Unwanted"),
            TableEntry.RANGE(min = 39, max = 40, result = "Defective"),
            TableEntry.RANGE(min = 41, max = 42, result = "Resolved"),
            TableEntry.RANGE(min = 43, max = 44, result = "Unexpected"),
            TableEntry.RANGE(min = 45, max = 46, result = "Public"),
            TableEntry.RANGE(min = 47, max = 48, result = "False"),
            TableEntry.RANGE(min = 49, max = 50, result = "Precarious"),
            TableEntry.RANGE(min = 51, max = 52, result = "Violated"),
            TableEntry.RANGE(min = 53, max = 54, result = "Logical"),
            TableEntry.RANGE(min = 55, max = 56, result = "Audacious"),
            TableEntry.RANGE(min = 57, max = 58, result = "Disputed"),
            TableEntry.RANGE(min = 59, max = 60, result = "Broken"),
            TableEntry.RANGE(min = 61, max = 62, result = "Confusing"),
            TableEntry.RANGE(min = 63, max = 64, result = "Intense"),
            TableEntry.RANGE(min = 65, max = 66, result = "Perilous"),
            TableEntry.RANGE(min = 67, max = 68, result = "Unknown"),
            TableEntry.RANGE(min = 69, max = 70, result = "Disconnected"),
            TableEntry.RANGE(min = 71, max = 72, result = "Protected"),
            TableEntry.RANGE(min = 73, max = 74, result = "Desired"),
            TableEntry.RANGE(min = 75, max = 76, result = "Functional"),
            TableEntry.RANGE(min = 77, max = 78, result = "Unstable"),
            TableEntry.RANGE(min = 79, max = 80, result = "Dangerous"),
            TableEntry.RANGE(min = 81, max = 82, result = "Imprisoned"),
            TableEntry.RANGE(min = 83, max = 84, result = "Exhausted"),
            TableEntry.RANGE(min = 85, max = 86, result = "Resilient"),
            TableEntry.RANGE(min = 87, max = 88, result = "Weakened"),
            TableEntry.RANGE(min = 89, max = 90, result = "Oppressive"),
            TableEntry.RANGE(min = 91, max = 92, result = "Distorted"),
            TableEntry.RANGE(min = 93, max = 94, result = "Abundant"),
            TableEntry.RANGE(min = 95, max = 96, result = "Changed"),
            TableEntry.RANGE(min = 97, max = 98, result = "Crystallized"),
            TableEntry.RANGE(min = 99, max = 100, result = "Weird"),
            // Last entry per spec: 99-100=Weird
        ),
    )

    val tables: List<TableDef> = listOf(action, description)
}
