@file:Suppress("MagicNumber")

package com.kleros.character

import com.kleros.table.TableEntry

object CharacterData {

    val descriptors: List<TableEntry> = listOf(
        TableEntry.DIRECT(1, "Academic"),
        TableEntry.DIRECT(2, "Aggressive"),
        TableEntry.DIRECT(3, "Agile"),
        TableEntry.DIRECT(4, "Artistic"),
        TableEntry.DIRECT(5, "Athletic"),
        TableEntry.DIRECT(6, "Authority"),
        TableEntry.DIRECT(7, "Awareness"),
        TableEntry.DIRECT(8, "Bizarre"),
        TableEntry.DIRECT(9, "Block"),
        TableEntry.DIRECT(10, "Body"),
        TableEntry.DIRECT(11, "Brave"),
        TableEntry.DIRECT(12, "Charm"),
        TableEntry.DIRECT(13, "Cheat"),
        TableEntry.DIRECT(14, "Collector"),
        TableEntry.DIRECT(15, "Combat"),
        TableEntry.DIRECT(16, "Common"),
        TableEntry.DIRECT(17, "Communication"),
        TableEntry.DIRECT(18, "Community"),
        TableEntry.DIRECT(19, "Comprehension"),
        TableEntry.DIRECT(20, "Conflict"),
        TableEntry.DIRECT(21, "Connection"),
        TableEntry.DIRECT(22, "Control"),
        TableEntry.DIRECT(23, "Create"),
        TableEntry.DIRECT(24, "Crude"),
        TableEntry.DIRECT(25, "Dangerous"),
        TableEntry.DIRECT(26, "Dark"),
        TableEntry.DIRECT(27, "Deceptive"),
        TableEntry.DIRECT(28, "Defense"),
        TableEntry.DIRECT(29, "Detect"),
        TableEntry.DIRECT(30, "Domestic"),
        TableEntry.DIRECT(31, "Education"),
        TableEntry.DIRECT(32, "Elements"),
        TableEntry.DIRECT(33, "Elite"),
        TableEntry.DIRECT(34, "Emotion"),
        TableEntry.DIRECT(35, "Endurance"),
        TableEntry.DIRECT(36, "Enemy"),
        TableEntry.DIRECT(37, "Energy"),
        TableEntry.DIRECT(38, "Enhanced"),
        TableEntry.DIRECT(39, "Entertain"),
        TableEntry.DIRECT(40, "Environment"),
        TableEntry.DIRECT(41, "Equipment"),
        TableEntry.DIRECT(42, "Exceptional"),
        TableEntry.DIRECT(43, "Executive"),
        TableEntry.DIRECT(44, "Experienced"),
        TableEntry.DIRECT(45, "Fast"),
        TableEntry.DIRECT(46, "Find"),
        TableEntry.DIRECT(47, "Finesse"),
        TableEntry.DIRECT(48, "Force"),
        TableEntry.DIRECT(49, "Guard"),
        TableEntry.DIRECT(50, "Guide"),
        TableEntry.DIRECT(51, "Harm"),
        TableEntry.DIRECT(52, "Heal"),
        TableEntry.DIRECT(53, "Helpful"),
        TableEntry.DIRECT(54, "Heritage"),
        TableEntry.DIRECT(55, "Heroic"),
        TableEntry.DIRECT(56, "Information"),
        TableEntry.DIRECT(57, "Insight"),
        TableEntry.DIRECT(58, "Intimidating"),
        TableEntry.DIRECT(59, "Knowledge"),
        TableEntry.DIRECT(60, "Lethal"),
        TableEntry.DIRECT(61, "Limitation"),
        TableEntry.DIRECT(62, "Locate"),
        TableEntry.DIRECT(63, "Medical"),
        TableEntry.DIRECT(64, "Melee"),
        TableEntry.DIRECT(65, "Military"),
        TableEntry.DIRECT(66, "Mind"),
        TableEntry.DIRECT(67, "Move"),
        TableEntry.DIRECT(68, "Mundane"),
        TableEntry.DIRECT(69, "Mysterious"),
        TableEntry.DIRECT(70, "Nature"),
        TableEntry.DIRECT(71, "Object"),
        TableEntry.DIRECT(72, "Obstacle"),
        TableEntry.DIRECT(73, "Offense"),
        TableEntry.DIRECT(74, "Official"),
        TableEntry.DIRECT(75, "Perception"),
        TableEntry.DIRECT(76, "Performance"),
        TableEntry.DIRECT(77, "Persona"),
        TableEntry.DIRECT(78, "Physical"),
        TableEntry.DIRECT(79, "Profession"),
        TableEntry.DIRECT(80, "Protection"),
        TableEntry.DIRECT(81, "Psionics"),
        TableEntry.DIRECT(82, "Ranged"),
        TableEntry.DIRECT(83, "Recon"),
        TableEntry.DIRECT(84, "Resistance"),
        TableEntry.DIRECT(85, "Resolve"),
        TableEntry.DIRECT(86, "Resources"),
        TableEntry.DIRECT(87, "Secrets"),
        TableEntry.DIRECT(88, "Speed"),
        TableEntry.DIRECT(89, "Stealth"),
        TableEntry.DIRECT(90, "Strength"),
        TableEntry.DIRECT(91, "Survival"),
        TableEntry.DIRECT(92, "Tech"),
        TableEntry.DIRECT(93, "Theft"),
        TableEntry.DIRECT(94, "Throwing"),
        TableEntry.DIRECT(95, "Tradition"),
        TableEntry.DIRECT(96, "Traps"),
        TableEntry.DIRECT(97, "Vehicle"),
        TableEntry.DIRECT(98, "Villainy"),
        TableEntry.DIRECT(99, "Warfare"),
        TableEntry.DIRECT(100, "Weapon"),
    )

    val statistics: List<TableEntry> = listOf(
        TableEntry.RANGE(1, 1, "About 50% lower"),
        TableEntry.RANGE(2, 3, "About 25% lower"),
        TableEntry.RANGE(4, 7, "What you expect"),
        TableEntry.RANGE(8, 9, "About 25% higher"),
        TableEntry.RANGE(10, 10, "About 50% higher"),
    )
}
