@file:Suppress("MagicNumber")

package com.kleros.mystery

import com.kleros.table.TableEntry

object MysteryData {

    val discoveryCheck: List<TableEntry.RANGE> = listOf(
        TableEntry.RANGE(1, 15, "Nothing useful found"),
        TableEntry.RANGE(16, 35, "New Suspect not connected"),
        TableEntry.RANGE(36, 50, "New Clue not connected"),
        TableEntry.RANGE(51, 70, "New Clue connected to a Suspect"),
        TableEntry.RANGE(71, 80, "New Suspect connected to a Clue"),
        TableEntry.RANGE(81, 100, "Connect existing Clue to existing Suspect"),
        TableEntry.RANGE(101, Int.MAX_VALUE, "Definitive clue: connected Suspect is the answer"),
    )

    val descriptors: List<TableEntry.DIRECT> = listOf(
        TableEntry.DIRECT(1, "Accident"),
        TableEntry.DIRECT(2, "Aggressive"),
        TableEntry.DIRECT(3, "Ambition"),
        TableEntry.DIRECT(4, "Anger"),
        TableEntry.DIRECT(5, "Attack"),
        TableEntry.DIRECT(6, "Betray"),
        TableEntry.DIRECT(7, "Bribe"),
        TableEntry.DIRECT(8, "Business"),
        TableEntry.DIRECT(9, "Change"),
        TableEntry.DIRECT(10, "Clothing"),
        TableEntry.DIRECT(11, "Code"),
        TableEntry.DIRECT(12, "Communication"),
        TableEntry.DIRECT(13, "Conflict"),
        TableEntry.DIRECT(14, "Container"),
        TableEntry.DIRECT(15, "Control"),
        TableEntry.DIRECT(16, "Cooperation"),
        TableEntry.DIRECT(17, "Damage"),
        TableEntry.DIRECT(18, "Danger"),
        TableEntry.DIRECT(19, "Deliberate"),
        TableEntry.DIRECT(20, "Deny"),
        TableEntry.DIRECT(21, "Desperate"),
        TableEntry.DIRECT(22, "Discarded"),
        TableEntry.DIRECT(23, "Discover"),
        TableEntry.DIRECT(24, "Dispute"),
        TableEntry.DIRECT(25, "Document"),
        TableEntry.DIRECT(26, "Domicile"),
        TableEntry.DIRECT(27, "Emotion"),
        TableEntry.DIRECT(28, "Empty"),
        TableEntry.DIRECT(29, "Enemy"),
        TableEntry.DIRECT(30, "Equipment"),
        TableEntry.DIRECT(31, "Fake"),
        TableEntry.DIRECT(32, "Family"),
        TableEntry.DIRECT(33, "Fear"),
        TableEntry.DIRECT(34, "Find"),
        TableEntry.DIRECT(35, "Flee"),
        TableEntry.DIRECT(36, "Friend"),
        TableEntry.DIRECT(37, "Give"),
        TableEntry.DIRECT(38, "Goal"),
        TableEntry.DIRECT(39, "Greed"),
        TableEntry.DIRECT(40, "Group"),
        TableEntry.DIRECT(41, "Harm"),
        TableEntry.DIRECT(42, "Hate"),
        TableEntry.DIRECT(43, "Help"),
        TableEntry.DIRECT(44, "Helpful"),
        TableEntry.DIRECT(45, "Hidden"),
        TableEntry.DIRECT(46, "Hurt"),
        TableEntry.DIRECT(47, "Inform"),
        TableEntry.DIRECT(48, "Information"),
        TableEntry.DIRECT(49, "Jealousy"),
        TableEntry.DIRECT(50, "Leadership"),
        TableEntry.DIRECT(51, "Legal"),
        TableEntry.DIRECT(52, "Lethal"),
        TableEntry.DIRECT(53, "Lies"),
        TableEntry.DIRECT(54, "Location"),
        TableEntry.DIRECT(55, "Locked"),
        TableEntry.DIRECT(56, "Lost"),
        TableEntry.DIRECT(57, "Love"),
        TableEntry.DIRECT(58, "Loyal"),
        TableEntry.DIRECT(59, "Mechanical"),
        TableEntry.DIRECT(60, "Misfortune"),
        TableEntry.DIRECT(61, "Missing"),
        TableEntry.DIRECT(62, "Mistake"),
        TableEntry.DIRECT(63, "Motive"),
        TableEntry.DIRECT(64, "Mundane"),
        TableEntry.DIRECT(65, "Mysterious"),
        TableEntry.DIRECT(66, "Nature"),
        TableEntry.DIRECT(67, "New"),
        TableEntry.DIRECT(68, "Night"),
        TableEntry.DIRECT(69, "NPC"),
        TableEntry.DIRECT(70, "Obligation"),
        TableEntry.DIRECT(71, "Old"),
        TableEntry.DIRECT(72, "Partial"),
        TableEntry.DIRECT(73, "PC"),
        TableEntry.DIRECT(74, "Personal"),
        TableEntry.DIRECT(75, "Plot"),
        TableEntry.DIRECT(76, "Portal"),
        TableEntry.DIRECT(77, "Possession"),
        TableEntry.DIRECT(78, "Power"),
        TableEntry.DIRECT(79, "Protect"),
        TableEntry.DIRECT(80, "Rare"),
        TableEntry.DIRECT(81, "Representative"),
        TableEntry.DIRECT(82, "Resource"),
        TableEntry.DIRECT(83, "Rumor"),
        TableEntry.DIRECT(84, "Science"),
        TableEntry.DIRECT(85, "Strange"),
        TableEntry.DIRECT(86, "Surprise"),
        TableEntry.DIRECT(87, "Suspicious"),
        TableEntry.DIRECT(88, "Take"),
        TableEntry.DIRECT(89, "Technology"),
        TableEntry.DIRECT(90, "Threaten"),
        TableEntry.DIRECT(91, "Tool"),
        TableEntry.DIRECT(92, "Travel"),
        TableEntry.DIRECT(93, "Trust"),
        TableEntry.DIRECT(94, "Unusual"),
        TableEntry.DIRECT(95, "Valuable"),
        TableEntry.DIRECT(96, "Vehicle"),
        TableEntry.DIRECT(97, "Vengeance"),
        TableEntry.DIRECT(98, "Wealth"),
        TableEntry.DIRECT(99, "Weapon"),
        TableEntry.DIRECT(100, "Witness"),
    )
}
