@file:Suppress("MagicNumber")

package com.kleros.location

import com.kleros.table.TableEntry

object LocationData {

    val descriptors: List<TableEntry> = listOf(
        TableEntry.DIRECT(1, "Abandoned"),
        TableEntry.DIRECT(2, "Active"),
        TableEntry.DIRECT(3, "Artistic"),
        TableEntry.DIRECT(4, "Atmosphere"),
        TableEntry.DIRECT(5, "Average"),
        TableEntry.DIRECT(6, "Beautiful"),
        TableEntry.DIRECT(7, "Bizarre"),
        TableEntry.DIRECT(8, "Bleak"),
        TableEntry.DIRECT(9, "Bright"),
        TableEntry.DIRECT(10, "Business"),
        TableEntry.DIRECT(11, "Clean"),
        TableEntry.DIRECT(12, "Clue"),
        TableEntry.DIRECT(13, "Cold"),
        TableEntry.DIRECT(14, "Colorful"),
        TableEntry.DIRECT(15, "Colorless"),
        TableEntry.DIRECT(16, "Communication"),
        TableEntry.DIRECT(17, "Complicated"),
        TableEntry.DIRECT(18, "Consumable"),
        TableEntry.DIRECT(19, "Container"),
        TableEntry.DIRECT(20, "Cramped"),
        TableEntry.DIRECT(21, "Creepy"),
        TableEntry.DIRECT(22, "Crude"),
        TableEntry.DIRECT(23, "Damaged"),
        TableEntry.DIRECT(24, "Dangerous"),
        TableEntry.DIRECT(25, "Dark"),
        TableEntry.DIRECT(26, "Deactivated"),
        TableEntry.DIRECT(27, "Deliberate"),
        TableEntry.DIRECT(28, "Desired"),
        TableEntry.DIRECT(29, "Domestic"),
        TableEntry.DIRECT(30, "Empty"),
        TableEntry.DIRECT(31, "Enclosed"),
        TableEntry.DIRECT(32, "Energy"),
        TableEntry.DIRECT(33, "Equipment"),
        TableEntry.DIRECT(34, "Familiar"),
        TableEntry.DIRECT(35, "Flora"),
        TableEntry.DIRECT(36, "Foreign"),
        TableEntry.DIRECT(37, "Forgotten"),
        TableEntry.DIRECT(38, "Fortified"),
        TableEntry.DIRECT(39, "Fragile"),
        TableEntry.DIRECT(40, "Fragrant"),
        TableEntry.DIRECT(41, "Friendly"),
        TableEntry.DIRECT(42, "Frightening"),
        TableEntry.DIRECT(43, "Full"),
        TableEntry.DIRECT(44, "Fungal"),
        TableEntry.DIRECT(45, "Guarded"),
        TableEntry.DIRECT(46, "Helpful"),
        TableEntry.DIRECT(47, "Hidden"),
        TableEntry.DIRECT(48, "Important"),
        TableEntry.DIRECT(49, "Impressive"),
        TableEntry.DIRECT(50, "Inactive"),
        TableEntry.DIRECT(51, "Large"),
        TableEntry.DIRECT(52, "Light"),
        TableEntry.DIRECT(53, "Lonely"),
        TableEntry.DIRECT(54, "Loud"),
        TableEntry.DIRECT(55, "Meaningful"),
        TableEntry.DIRECT(56, "Mechanical"),
        TableEntry.DIRECT(57, "Messy"),
        TableEntry.DIRECT(58, "Moving"),
        TableEntry.DIRECT(59, "Multiple"),
        TableEntry.DIRECT(60, "Mundane"),
        TableEntry.DIRECT(61, "Mysterious"),
        TableEntry.DIRECT(62, "Natural"),
        TableEntry.DIRECT(63, "Neglected"),
        TableEntry.DIRECT(64, "Odd"),
        TableEntry.DIRECT(65, "Official"),
        TableEntry.DIRECT(66, "Old"),
        TableEntry.DIRECT(67, "Open"),
        TableEntry.DIRECT(68, "Ornate"),
        TableEntry.DIRECT(69, "Peaceful"),
        TableEntry.DIRECT(70, "Personal"),
        TableEntry.DIRECT(71, "Portal"),
        TableEntry.DIRECT(72, "Powerful"),
        TableEntry.DIRECT(73, "Prized"),
        TableEntry.DIRECT(74, "Protected"),
        TableEntry.DIRECT(75, "Purposeful"),
        TableEntry.DIRECT(76, "Quiet"),
        TableEntry.DIRECT(77, "Rare"),
        TableEntry.DIRECT(78, "Ready"),
        TableEntry.DIRECT(79, "Reassuring"),
        TableEntry.DIRECT(80, "Resource"),
        TableEntry.DIRECT(81, "Rustic"),
        TableEntry.DIRECT(82, "Simple"),
        TableEntry.DIRECT(83, "Small"),
        TableEntry.DIRECT(84, "Storage"),
        TableEntry.DIRECT(85, "Strange"),
        TableEntry.DIRECT(86, "Threat"),
        TableEntry.DIRECT(87, "Tiny"),
        TableEntry.DIRECT(88, "Tool"),
        TableEntry.DIRECT(89, "Tragic"),
        TableEntry.DIRECT(90, "Unpleasant"),
        TableEntry.DIRECT(91, "Unusual"),
        TableEntry.DIRECT(92, "Useful"),
        TableEntry.DIRECT(93, "Valuable"),
        TableEntry.DIRECT(94, "Vast"),
        TableEntry.DIRECT(95, "Warm"),
        TableEntry.DIRECT(96, "Warning"),
        TableEntry.DIRECT(97, "Watery"),
        TableEntry.DIRECT(98, "Weapon"),
        TableEntry.DIRECT(99, "Welcoming"),
        TableEntry.DIRECT(100, "Winding"),
    )

    val elements: List<TableEntry> = listOf(
        TableEntry.RANGE(2, 4, "None"),
        TableEntry.RANGE(5, 9, "Expected"),
        TableEntry.RANGE(10, 10, "Expected, Return"),
        TableEntry.RANGE(11, 14, "Random"),
        TableEntry.RANGE(15, 15, "Random, Hazard"),
        TableEntry.RANGE(16, 16, "Random, Discovery"),
        TableEntry.RANGE(17, 19, "Known"),
        TableEntry.RANGE(20, 20, "Known, Climax"),
        TableEntry.RANGE(21, 21, "Expected, Exit"),
        TableEntry.RANGE(22, 30, "Complete"),
    )
}
