@file:Suppress("MagicNumber")

package com.kleros.creature

import com.kleros.table.TableEntry

object CreatureData {

    val descriptors: List<TableEntry> = listOf(
        // Left column 1-50
        TableEntry.DIRECT(1, "Amorphous"),
        TableEntry.DIRECT(2, "Loud"),
        TableEntry.DIRECT(3, "Loud"),
        TableEntry.DIRECT(4, "Aquatic"),
        TableEntry.DIRECT(5, "Armed"),
        TableEntry.DIRECT(6, "Armored"),
        TableEntry.DIRECT(7, "Artificial"),
        TableEntry.DIRECT(8, "Avian"),
        TableEntry.DIRECT(9, "Beautiful"),
        TableEntry.DIRECT(10, "Brutish"),
        TableEntry.DIRECT(11, "Chemical"),
        TableEntry.DIRECT(12, "Chemical"),
        TableEntry.DIRECT(13, "Cloud"),
        TableEntry.DIRECT(14, "Cloud"),
        TableEntry.DIRECT(15, "Cold"),
        TableEntry.DIRECT(16, "Cold"),
        TableEntry.DIRECT(17, "Conceal"),
        TableEntry.DIRECT(18, "Conceal"),
        TableEntry.DIRECT(19, "Constrain"),
        TableEntry.DIRECT(20, "Constrain"),
        TableEntry.DIRECT(21, "Control"),
        TableEntry.DIRECT(22, "Control"),
        TableEntry.DIRECT(23, "Counteract"),
        TableEntry.DIRECT(24, "Counteract"),
        TableEntry.DIRECT(25, "Create"),
        TableEntry.DIRECT(26, "Create"),
        TableEntry.DIRECT(27, "Damage"),
        TableEntry.DIRECT(28, "Damage"),
        TableEntry.DIRECT(29, "Deceive"),
        TableEntry.DIRECT(30, "Deceive"),
        TableEntry.DIRECT(31, "Defense"),
        TableEntry.DIRECT(32, "Defense"),
        TableEntry.DIRECT(33, "Destroy"),
        TableEntry.DIRECT(34, "Destroy"),
        TableEntry.DIRECT(35, "Detect"),
        TableEntry.DIRECT(36, "Detect"),
        TableEntry.DIRECT(37, "Distance"),
        TableEntry.DIRECT(38, "Distance"),
        TableEntry.DIRECT(39, "Duplicate"),
        TableEntry.DIRECT(40, "Duplicate"),
        TableEntry.DIRECT(41, "Emission"),
        TableEntry.DIRECT(42, "Emission"),
        TableEntry.DIRECT(43, "Energy"),
        TableEntry.DIRECT(44, "Energy"),
        TableEntry.DIRECT(45, "Elements"),
        TableEntry.DIRECT(46, "Elements"),
        TableEntry.DIRECT(47, "Environment"),
        TableEntry.DIRECT(48, "Environment"),
        TableEntry.DIRECT(49, "Extra"),
        TableEntry.DIRECT(50, "Extra"),
        // Right column 51-100 from the actual doc
        TableEntry.DIRECT(51, "Limbs"),
        TableEntry.DIRECT(52, "Mammalian"),
        TableEntry.DIRECT(53, "Animal"),
        TableEntry.DIRECT(54, "Mandibles"),
        TableEntry.DIRECT(55, "Markings"),
        TableEntry.DIRECT(56, "Mechanical"),
        TableEntry.DIRECT(57, "Metallic"),
        TableEntry.DIRECT(58, "Mighty"),
        TableEntry.DIRECT(59, "Mouth"),
        TableEntry.DIRECT(60, "Movement"),
        TableEntry.DIRECT(61, "Multiple"),
        TableEntry.DIRECT(62, "Muscular"),
        TableEntry.DIRECT(63, "Mysterious"),
        TableEntry.DIRECT(64, "Natural"),
        TableEntry.DIRECT(65, "Nightmarish"),
        TableEntry.DIRECT(66, "Obscured"),
        TableEntry.DIRECT(67, "Pale"),
        TableEntry.DIRECT(68, "Plant"),
        TableEntry.DIRECT(69, "Powered"),
        TableEntry.DIRECT(70, "Powerful"),
        TableEntry.DIRECT(71, "Reptilian"),
        TableEntry.DIRECT(72, "Scales"),
        TableEntry.DIRECT(73, "Shambling"),
        TableEntry.DIRECT(74, "Silent"),
        TableEntry.DIRECT(75, "Sinister"),
        TableEntry.DIRECT(76, "Slow"),
        TableEntry.DIRECT(77, "Small"),
        TableEntry.DIRECT(78, "Solitary"),
        TableEntry.DIRECT(79, "Spiked"),
        TableEntry.DIRECT(80, "Stationary"),
        TableEntry.DIRECT(81, "Steaming"),
        TableEntry.DIRECT(82, "Sticky"),
        TableEntry.DIRECT(83, "Stinger"),
        TableEntry.DIRECT(84, "Strange"),
        TableEntry.DIRECT(85, "Tail"),
        TableEntry.DIRECT(86, "Tall"),
        TableEntry.DIRECT(87, "Tentacled"),
        TableEntry.DIRECT(88, "Tongue"),
        TableEntry.DIRECT(89, "Toothy"),
        TableEntry.DIRECT(90, "Transparent"),
        TableEntry.DIRECT(91, "Twisted"),
        TableEntry.DIRECT(92, "Unnatural"),
        TableEntry.DIRECT(93, "Verbal"),
        TableEntry.DIRECT(94, "Warm"),
        TableEntry.DIRECT(95, "Watery"),
        TableEntry.DIRECT(96, "Weak"),
        TableEntry.DIRECT(97, "Weapon"),
        TableEntry.DIRECT(98, "Wings"),
        TableEntry.DIRECT(99, "Wormish"),
        TableEntry.DIRECT(100, "Young"),
    )

    val abilities: List<TableEntry> = listOf(
        TableEntry.RANGE(1, 2, "Absorb"),
        TableEntry.RANGE(3, 4, "Attach"),
        TableEntry.RANGE(5, 6, "Attack"),
        TableEntry.RANGE(7, 8, "Bypass"),
        TableEntry.RANGE(9, 10, "Change"),
        TableEntry.RANGE(11, 12, "Chemical"),
        TableEntry.RANGE(13, 14, "Cloud"),
        TableEntry.RANGE(15, 16, "Cold"),
        TableEntry.RANGE(17, 18, "Conceal"),
        TableEntry.RANGE(19, 20, "Constrain"),
        TableEntry.RANGE(21, 22, "Control"),
        TableEntry.RANGE(23, 24, "Counteract"),
        TableEntry.RANGE(25, 26, "Create"),
        TableEntry.RANGE(27, 28, "Damage"),
        TableEntry.RANGE(29, 30, "Deceive"),
        TableEntry.RANGE(31, 32, "Defense"),
        TableEntry.RANGE(33, 34, "Destroy"),
        TableEntry.RANGE(35, 36, "Detect"),
        TableEntry.RANGE(37, 38, "Distance"),
        TableEntry.RANGE(39, 40, "Duplicate"),
        TableEntry.RANGE(41, 42, "Emission"),
        TableEntry.RANGE(43, 44, "Energy"),
        TableEntry.RANGE(45, 46, "Elements"),
        TableEntry.RANGE(47, 48, "Extra"),
        TableEntry.RANGE(49, 50, "Environment"),
        TableEntry.RANGE(51, 52, "Fire"),
        TableEntry.RANGE(53, 54, "Flight"),
        TableEntry.RANGE(55, 56, "Fangs"),
        TableEntry.RANGE(57, 58, "Frightening"),
        TableEntry.RANGE(59, 60, "Heat"),
        TableEntry.RANGE(61, 62, "Heal"),
        TableEntry.RANGE(63, 64, "Illness"),
        TableEntry.RANGE(65, 66, "Mental"),
        TableEntry.RANGE(67, 68, "Minor"),
        TableEntry.RANGE(69, 70, "Object"),
        TableEntry.RANGE(71, 72, "Pain"),
        TableEntry.RANGE(73, 74, "Perception"),
        TableEntry.RANGE(75, 76, "Poison"),
        TableEntry.RANGE(77, 78, "Radius"),
        TableEntry.RANGE(79, 80, "Resistance"),
        TableEntry.RANGE(81, 82, "Stealth"),
        TableEntry.RANGE(83, 84, "Skill"),
        TableEntry.RANGE(85, 86, "Strange"),
        TableEntry.RANGE(87, 88, "Summon"),
        TableEntry.RANGE(89, 90, "Suppress"),
        TableEntry.RANGE(91, 92, "Travel"),
        TableEntry.RANGE(93, 94, "Unnatural"),
        TableEntry.RANGE(95, 96, "Water"),
        TableEntry.RANGE(97, 98, "Weakness"),
        TableEntry.RANGE(99, 100, "Strength"),
    )

    val initialBehavior: List<TableEntry> = listOf(
        TableEntry.DIRECT(1, "Inert, motionless"),
        TableEntry.DIRECT(2, "Moving, traveling"),
        TableEntry.DIRECT(3, "Moving, traveling"),
        TableEntry.DIRECT(4, "Wary and alert"),
        TableEntry.DIRECT(5, "Friendly"),
        TableEntry.DIRECT(6, "Attacking, aggressive"),
        TableEntry.DIRECT(7, "Feeding"),
        TableEntry.DIRECT(8, "Working, doing something"),
        TableEntry.DIRECT(9, "Defensive, protecting itself"),
        TableEntry.DIRECT(10, "Exhibits an Ability"),
    )

    val newBehavior: List<TableEntry> = listOf(
        TableEntry.DIRECT(1, "Acts as expected"),
        TableEntry.DIRECT(2, "Acts as expected"),
        TableEntry.DIRECT(3, "Acts as expected"),
        TableEntry.DIRECT(4, "Acts as expected"),
        TableEntry.DIRECT(5, "Acts as expected"),
        TableEntry.DIRECT(6, "Acts as expected"),
        TableEntry.DIRECT(7, "Next expected step"),
        TableEntry.DIRECT(8, "Next expected step"),
        TableEntry.DIRECT(9, "Roll on Initial Behavior"),
        TableEntry.DIRECT(10, "Exhibits an Ability"),
    )
}
